// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParcAuto.Data;

#nullable disable

namespace ParcAuto.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250105112029_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ParcAuto.Models.Client", b =>
                {
                    b.Property<int>("ID_Client")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Client"));

                    b.Property<string>("CNP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data_Inregistrarii")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Client");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("ParcAuto.Models.Factura", b =>
                {
                    b.Property<int>("ID_Factura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Factura"));

                    b.Property<DateTime>("Data_Emitere")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Rezervare")
                        .HasColumnType("int");

                    b.Property<string>("Status_Plata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Suma_Totala")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID_Factura");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("ParcAuto.Models.Mentenanta", b =>
                {
                    b.Property<int>("ID_Mentenanta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Mentenanta"));

                    b.Property<decimal>("Cost_Estimativ")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Data_Programare")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Vehicul")
                        .HasColumnType("int");

                    b.Property<string>("Tip_Interventie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Mentenanta");

                    b.ToTable("Mentenantas");
                });

            modelBuilder.Entity("ParcAuto.Models.Rezervare", b =>
                {
                    b.Property<int>("ID_Rezervare")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Rezervare"));

                    b.Property<DateTime>("Data_Sfarsit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Data_Start")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Client")
                        .HasColumnType("int");

                    b.Property<int>("ID_Vehicul")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Rezervare");

                    b.ToTable("Rezervares");
                });

            modelBuilder.Entity("ParcAuto.Models.Vehicle", b =>
                {
                    b.Property<int>("ID_Vehicul")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Vehicul"));

                    b.Property<int>("An_Fabricatie")
                        .HasColumnType("int");

                    b.Property<int>("Kilometraj")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stare")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tip_Combustibil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Vehicul");

                    b.ToTable("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
